Rebase from 'release/rolling/librealsense2'

diff --git a/.github/workflows/static_analysis.yaml b/.github/workflows/static_analysis.yaml
--- a/.github/workflows/static_analysis.yaml
+++ b/.github/workflows/static_analysis.yaml
@@ -5,13 +5,16 @@ on:
     branches: ['**']
   pull_request:
     branches: ['**']
+    
+permissions: read-all
 
 jobs:
-  cppcheck:
-    name: cppcheck
+  CppCheck:
+    name: CppCheck
+    timeout-minutes: 30
     runs-on: ubuntu-22.04
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
 
       - name: Install 
         shell: bash
@@ -61,7 +64,7 @@ jobs:
             &&  echo "No diffs found in cppcheck_run.parsed.log"
 
       - name: Upload logs
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 #v4
         with: 
           name: cppcheck_log
           path: |
@@ -94,3 +97,231 @@ jobs:
           echo "see the diff step above, or the 'cppcheck_log' artifact (under Summary) for details"
           echo "commit all files in the artifact to .github/workflows/ if these are valid results"
           exit 1
+#---------------------------------------------------------------------------------------------------#
+  ValgrindCheck:
+    name: Valgrind Memory Leak Check
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
+      
+      - name: Install Valgrind
+        run: |
+          sudo apt-get update;
+          sudo apt-get install -qq build-essential xorg-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev libglm-dev;
+          sudo apt-get install -qq libusb-1.0-0-dev;
+          sudo apt-get install -qq libgtk-3-dev;
+          sudo apt-get install libglfw3-dev libglfw3;
+          sudo apt-get install -y valgrind
+
+      - name: Move files into examples folder in order to build automaticly
+        run: |
+            sudo mv .github/workflows/memory-leaks-check examples/
+
+      - name: Modify CMakeLists.txt
+        run: |
+          # Path to the CMakeLists.txt file
+          CMAKE_FILE=./examples/CMakeLists.txt
+
+          # Check if the line already exists to avoid duplicates
+          if ! grep -q "add_subdirectory(memory-leaks-check)" "$CMAKE_FILE"; then
+            # Add the line before the first occurrence of 'add_subdirectory(hello-realsense)'
+            sed -i '/add_subdirectory(hello-realsense)/i add_subdirectory(memory-leaks-check)' "$CMAKE_FILE"
+          fi
+      
+      - name: Build Application
+        run: |
+          mkdir build
+          cd build
+          cmake .. -DBUILD_EXAMPLES=true
+          make -j$(($(nproc)-1))
+      
+      - name: Run Valgrind
+        run: |
+          cd build
+          valgrind --leak-check=yes --show-leak-kinds=all --track-origins=yes --log-file=valgrind-out.txt ./Release/mem-leak-test
+        continue-on-error: true
+      
+      - name: Upload Valgrind log
+        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 #v4
+        with:
+          name: valgrind-log
+          path: build/valgrind-out.txt
+
+      - name: Check Valgrind Results
+        run: |
+            if grep -q "ERROR SUMMARY: [^0]" build/valgrind-out.txt; then
+                echo "Valgrind detected errors with backend."
+                exit 1
+            else
+                echo "No errors detected by Valgrind with backend."
+            fi
+  ASANCheck: 
+    name: ASAN Memory Leak Check
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
+    
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update;
+        sudo apt-get install -qq build-essential xorg-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev libglm-dev;
+        sudo apt-get install -qq libusb-1.0-0-dev;
+        sudo apt-get install -qq libgtk-3-dev;
+        sudo apt-get install libglfw3-dev libglfw3;
+
+    - name: Move files into examples folder in order to build automaticly
+      run: |
+            sudo mv .github/workflows/memory-leaks-check examples/
+
+    - name: Modify CMakeLists.txt
+      run: |
+        # Path to the CMakeLists.txt file
+        CMAKE_FILE=./examples/CMakeLists.txt
+
+        # Check if the line already exists to avoid duplicates
+        if ! grep -q "add_subdirectory(memory-leaks-check)" "$CMAKE_FILE"; then
+        # Add the line before the first occurrence of 'add_subdirectory(hello-realsense)'
+        sed -i '/add_subdirectory(hello-realsense)/i add_subdirectory(memory-leaks-check)' "$CMAKE_FILE"
+        fi
+
+    - name: Build Application with ASAN
+      run: |
+        mkdir build
+        cd build
+        cmake .. -DBUILD_EXAMPLES=true -DBUILD_ASAN=true
+        make -j$(($(nproc)-1))
+
+    - name: Run ASAN
+      run: |
+        cd build
+        ASAN_OPTIONS=halt_on_error=0:detect_leaks=1:log_path=asan-out.txt ./Release/mem-leak-test
+      continue-on-error: true
+
+    - name: Upload ASAN log
+      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
+      with:
+          name: asan-log
+          path: build/asan-out.txt*
+
+    - name: Check ASAN Results
+      run: |
+            # Use a wildcard to match the file with any number appended
+            ASAN_FILE=$(ls build/asan-out.txt* 2>/dev/null || true)
+            if [ -n "$ASAN_FILE" ]; then
+                if grep -q "SUMMARY: AddressSanitizer:" "$ASAN_FILE"; then
+                    echo "ASAN detected memory leaks."
+                    exit 1
+                else
+                    echo "No memory leaks detected by ASAN."
+                fi
+            else
+                echo "No ASAN output file found. No errors detected."
+            fi
+  # We verify the minimal CMake version we support is preserved when building with default CMake flags
+  minimal_cmake_version:
+    name: "Minimal CMake version"
+    timeout-minutes: 30
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
+
+      - name: "Install Dependencies"
+        run: |
+          work_dir=$(pwd)       
+          # Go back from RealSense directory to parent directory  
+          cd ..
+          
+          git clone https://github.com/nlohmann/cmake_min_version.git
+          cd cmake_min_version
+          # We clone a specific commit which we tested the process as working
+          git checkout 687dc56e1cf52c865cebf6ac94ad67906d6e1369
+          
+          echo "Install LibRealSense pre-installed packages requirements"
+          sudo apt-get update 
+          sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev at
+          
+          python3 -mvenv venv
+          venv/bin/pip3 install -r requirements.txt
+          
+      - name: "Get Current CMake version"
+        id: cmake_version
+        run: |
+          work_dir=$(pwd)
+          cd ..
+          
+          cd cmake_min_version
+          venv/bin/python3 cmake_downloader.py --first_minor
+          output=$(venv/bin/python3 cmake_min_version.py $work_dir)
+          
+          # Sample of Expected Output of cmake_min_version.py ***
+          # [  0%] CMake 3.9.2    ✔ works
+          # [ 12%] CMake 3.2.2    ✘ error
+          #        CMakeLists.txt:7 (cmake_minimum_required)
+          # [ 33%] CMake 3.8.0    ✔ works
+          # [ 50%] CMake 3.7.1    ✘ error
+          #        CMakeLists.txt:16 (target_compile_features)
+          # [ 80%] CMake 3.7.2    ✘ error
+          #        CMakeLists.txt:16 (target_compile_features)
+          # [100%] Minimal working version: CMake 3.8.0
+          
+          # cmake_minimum_required(VERSION 3.8.0)
+          
+          echo "$output"
+                    
+          # Retrieve CMake minimal version from the last line of the tool output.
+          current_cmake_version=$(echo ${output} | grep -oP "VERSION \d+\.\d+" || echo "VERSION NOT FOUND")
+          
+          if [ "$current_cmake_version" == "VERSION NOT FOUND" ]
+          then
+            echo "Error - CMake version not found."
+            exit 1
+          fi
+          
+          current_cmake_major_ver=$(echo $current_cmake_version | grep -oP "\d+\.\d+" | cut -d'.' -f 1)
+          current_cmake_minor_ver=$(echo $current_cmake_version | grep -oP "\d+\.\d+" | cut -d'.' -f 2)
+          
+          # Saving cmake output in GitHub output
+          echo "current_cmake_major_ver=$current_cmake_major_ver" >> $GITHUB_OUTPUT
+          echo "current_cmake_minor_ver=$current_cmake_minor_ver" >> $GITHUB_OUTPUT
+        
+      - name: "Check minimal CMake version"
+        env:
+          EXPECTED_CMAKE_MAJOR_VER: 3
+          EXPECTED_CMAKE_MINOR_VER: 8
+          CURRENT_CMAKE_MAJOR_VER: ${{ steps.cmake_version.outputs.current_cmake_major_ver }}
+          CURRENT_CMAKE_MINOR_VER: ${{ steps.cmake_version.outputs.current_cmake_minor_ver }}
+
+        run: |
+          if [ $CURRENT_CMAKE_MAJOR_VER -lt ${EXPECTED_CMAKE_MAJOR_VER} ]
+          then
+            STATUS="PASSED"
+          elif [ $CURRENT_CMAKE_MAJOR_VER -eq ${EXPECTED_CMAKE_MAJOR_VER} ] && [ $CURRENT_CMAKE_MINOR_VER -eq ${EXPECTED_CMAKE_MINOR_VER} ]
+          then
+            STATUS="PASSED"
+          elif [ $CURRENT_CMAKE_MAJOR_VER -eq ${EXPECTED_CMAKE_MAJOR_VER} ] && [ $CURRENT_CMAKE_MINOR_VER -lt ${EXPECTED_CMAKE_MINOR_VER} ]
+          then
+            STATUS="PASSED"
+          else
+            STATUS="FAILED"
+          fi
+          
+          if [ $STATUS == "PASSED" ]
+          then
+            echo "The test PASSED, current CMake version is $CURRENT_CMAKE_MAJOR_VER.$CURRENT_CMAKE_MINOR_VER and it is not higher than VERSION ${EXPECTED_CMAKE_MAJOR_VER}.${EXPECTED_CMAKE_MINOR_VER}"
+          else
+            echo "Error - The minimal CMake version required for LibRS is ${EXPECTED_CMAKE_MAJOR_VER}.${EXPECTED_CMAKE_MINOR_VER} but on this build the minimal CMake version that works is $CURRENT_CMAKE_MAJOR_VER.$CURRENT_CMAKE_MINOR_VER"
+            exit 1
+          fi              
+
+  build_flags_docs:
+    name: "Generate build-flags.html"
+    timeout-minutes: 10
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
+
+      - name: Build docs 
+        run: |
+            python3 scripts/lrs_options-to-html.py
